version: "3.8"

services:
  flask1:
    build: ./app
    container_name: flask1
    environment:
      - FLASK_ENV=production
    networks:  
      - app_net

  flask2:
    build: ./app
    container_name: flask2
    environment:
      - FLASK_ENV=production
    networks:  
      - app_net

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask1
      - flask2
    networks:  
      - app_net

networks: 
  app_net:
    driver: bridge