---
all:
  children:
    web_servers:
      hosts:
        web1:
          ansible_host: 192.168.49.1
          ansible_user: devops_user
          ansible_password: "123456"
          ansible_become_password: "123456"
          ansible_connection: ssh
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'